import posixpath

'''
DISCLAIMER:
THIS CLASS IS USED FOR AT-SCALE-API, NOT FOR FLASK API
'''

class Route:
    BASE = "api/v1"
    AMDQL = posixpath.join(BASE, "amdql")
    API_KEY = posixpath.join(BASE, "api_key")
    AUDIT_LOG = posixpath.join(BASE, "audit_logs")
    BATCH_RANK = posixpath.join(BASE, "batch_rank")
    BATCH_UTILIZATION = posixpath.join(BASE, "batch/utilization")
    CALLBACK_TRIGGER = posixpath.join(BASE, "callback_trigger")
    CONFIG = posixpath.join(BASE, "config")
    CONFIG_MERGE = posixpath.join(BASE, "config/merge")
    DATA_BACKED_PROJECT = posixpath.join(BASE, "data_backed")
    DATA_BACKED_PROJECT_FILES = posixpath.join(BASE, "data_backed/files")
    DATA_BACKED_QUEUE = posixpath.join(DATA_BACKED_PROJECT, "queue")
    EXECUTOR_PAYLOAD = posixpath.join(BASE, "executor/payload")
    # DEPRECATED
    JENKINS_ABORT = posixpath.join(BASE, "job/abort")
    JENKINS_JOB = posixpath.join(BASE, "job_jenkins")
    JENKINS_KILL = posixpath.join(BASE, "job/kill")
    ######
    JOB_ABORT = posixpath.join(BASE, "job/abort")
    JOB_KILL = posixpath.join(BASE, "job/kill")
    JOB = posixpath.join(BASE, "job")
    JOB_FINALIZE = posixpath.join(BASE, "job/finalize")
    JOB_PREEMPT = posixpath.join(BASE, "job/preempt")
    JOB_QUEUED = posixpath.join(BASE, "job/queued")
    JOB_RUNNING = posixpath.join(BASE, "job/running")
    JOB_PENDING = posixpath.join(BASE, "job/pending")
    JOB_REQUEUE = posixpath.join(BASE, "job/requeue")
    JOB_LOG = posixpath.join(BASE, "job_log")
    JOB_PURGE = posixpath.join(BASE, "job_purge")
    JOB_SET = posixpath.join(BASE, "job_set")
    JOB_SET_ABORT = posixpath.join(BASE, "job_set/abort")
    JOB_STAGE = posixpath.join(BASE, "job_stage")
    JOB_STARTED_EXECUTION = posixpath.join(BASE, "job/status/started_execution")
    LOGIN = posixpath.join(BASE, "auth/login")
    MIDDLEWARE_HOST_UPDATE = posixpath.join(BASE, "middleware/update")
    NEXT_JOB = posixpath.join(BASE, "job_next")
    PLATFORM = posixpath.join(BASE, "system/platforms")
    POOL = posixpath.join(BASE, "pool")
    POOL_CURRENT_UTILIZATION = posixpath.join(POOL, "current_utilization")
    PYPI_PACKAGE = posixpath.join(BASE, "pypi")
    PYTHON_PACKAGE = posixpath.join(BASE, "python_package")
    RAW_CONFIG_MERGE = posixpath.join(BASE, "config/merge/raw")
    RESERVATION = posixpath.join(BASE, "calendar/reservation")
    RESERVATION_PLAN = posixpath.join(BASE, "calendar/reservation/plan")
    RESERVATION_SUPERUSER_OVERRIDE = posixpath.join(
        BASE, "calendar/reservation/superuser_override"
    )
    RESERVATION_WARNING = posixpath.join(RESERVATION, "warning")
    RESOURCE = posixpath.join(BASE, "calendar/resource")
    SSH_KEY = posixpath.join(BASE, "user/ssh_keys")
    STACK_SETUP = posixpath.join(BASE, "stack_setup")
    SYSTEM = posixpath.join(BASE, "system")
    SYSTEM_ACCESS = posixpath.join(SYSTEM, "access")
    SYSTEM_DATA = posixpath.join(SYSTEM, "data")
    SYSTEM_CONFIG_SNAPSHOT = posixpath.join(SYSTEM, "config_snapshot")
    SYSTEM_LABEL = posixpath.join(SYSTEM, "labels")
    SYSTEM_HISTORICAL_COUNTS = posixpath.join(SYSTEM, "pool_apu_count")
    SYSTEM_STATE = posixpath.join(SYSTEM, "states")
    SYSTEM_ENABLE = posixpath.join(SYSTEM, "enable")
    SYSTEM_DISABLE = posixpath.join(SYSTEM, "disable")
    TEAM = posixpath.join(BASE, "team")
    TEAM_ALLOCATION = posixpath.join(BASE, "team_allocation")
    TEST_CASE = posixpath.join(BASE, "test_case")
    TEST_CASE_TYPE = posixpath.join(TEST_CASE, "types")
    TEST_LIST = posixpath.join(BASE, "test_list")
    TEST_PURGE_DB = posixpath.join(BASE, "conductor_test/purge_db")
    UPLOAD = posixpath.join(BASE, "upload")
    USER = posixpath.join(BASE, "user")
    ERROR_DATA = posixpath.join(BASE, "error_data")
    ERROR_COLLECTIONS = posixpath.join(ERROR_DATA, "error_collections")
    ERROR_ARTIFACTS = posixpath.join(ERROR_DATA, "error_artifacts")
    MAAS_BOOT_RESOURCES = posixpath.join(BASE, "maas/boot_resources")
    LOCALE = posixpath.join(BASE, "locale")

